Behavioural tests
graknlabs/client-nodejs pull request #127
Opened 2020-12-17 09:42 UTC by Phillammon

## What is the goal of this PR?

We introduced behavioural tests in alignment with the behavioural tests present in our other clients and core server.

## What are the changes implemented in this PR?

Going to fill this out when the full extent of the changes are known

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +set -e
Setting -e means that everything else gets echoed

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +CORE_DISTRO=$1
First argument passed in is the location of the grakn core server artifact

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +fi
If there's already a distribution here (somehow), we definitely want to clear it- this SHOULDN'T be possible, but was in the previous testrunner, and if somehow quarantine is breached it's needed for safety.

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +fi
Extract the supplied distribution into a known folder.

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +sleep 10
Start up the server and wait 10 seconds for it to actually start.

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +tar -xf client-nodejs.tar.gz
Unarchive the client tarball that we created via compiling the client further up.

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +cp -LR ./test ./materialised-test
The tests are all symlinked in but need to reference the client directly. Consequently, we need to materialise the symlinks through cp -LR, materialising the files in this workspace and making them correctly reference the location of the client.

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +node ./node_modules/.bin/cucumber-js ./external/graknlabs_behaviour/**/*.feature --require './**/*.js' && export RESULT=0 || export RESULT=1
Run the actual cucumber tests over all available features using all js files in the workspace as requirements. If we succeed, result 0, if we fail, result 1, but crucially DO NOT TERMINATE EITHER WAY (Set +x is already set, meaning ordinarily a non-zero exit code would terminate the script with that exit code, but we need that not to happen here)

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +kill $(jps | awk '/GraknServer/ {print $1}')
Kill the server by searching jps (java ps) for graknserver and killing that PID (this is why we needed not to terminate immediately after the tests conclude)

2021-01-07 17:28 UTC, Phillammon commented on test/behaviour/cucumber_test.sh
> +exit $RESULT
aaaand exit with the result.

2021-01-07 17:41 UTC, Phillammon commented on test/behaviour/connection/database/BUILD
> +        "//test/behaviour/graql/language/define:DefineSteps.js",
This test nonobviously depends on define as it needs to perform a query of some kind to check if a transaction is operable, which is why this is here.

2021-01-07 18:19 UTC, alexjpwalker requested changes
Let's try to get rid of the generated .d.ts and .js files- they shouldn't really be checked in.

2021-01-07 18:19 UTC, alexjpwalker commented on test/behaviour/connection/session/SessionSteps.ts
> +    return (sessions.length === 0) === isNull;
Change this to match the Java implementation, which is roughly
```js
for (const session of sessions) {
    assert.ok(!!session === isNull);
}
```

2021-01-07 18:19 UTC, alexjpwalker commented on test/behaviour/util/Util.ts
> +}
```suggestion
}

```

2021-01-07 18:19 UTC, alexjpwalker commented on test/behaviour/util/Util.ts
> +        await testfunc();
I'm surprised this compiles- shouldn't `testfunc` have type `() => Promise<void>`? (and the same below)

2021-01-08 16:40 UTC, Phillammon commented on test/behaviour/util/Util.ts
> +        await testfunc();
You're correct- it compiles because everything happily casts down to void.

2021-01-08 17:15 UTC, alexjpwalker commented on BUILD
> +    visibility = ["//visibility:public"],
Let's add a comment here explaining why the rule to compile for test is different to the one for live?

2021-01-08 17:15 UTC, alexjpwalker commented on test/behaviour/util/Util.ts
> +        await testfunc();
I think we want to be as type safe as possible. What happens if we call `await` on a function that doesn't return a `Promise`, but rather just returns an `int`, or `void`?

2021-01-08 17:47 UTC, Phillammon commented on test/behaviour/util/Util.ts
> +        await testfunc();
Just executes directly

2021-01-08 18:19 UTC, alexjpwalker approved these changes

2021-01-08 18:23 UTC, merged